### ISSUE TITLE
Default logging still includes debug messages

### ISSUE THREAD

**Issue by aomarks** [Polymer/koa-node-resolve#17]
With `1.0.0-pre.4` and the default logging options, I'm still getting debug-level console messages for every module resolution, like:

```
[koa-node-resolve] Resolved Node module specifier "lit-element" to "../../node_modules/lit-element/lit-element.js"
```

**Comment by usergenic** [comment]
🤦‍♂️

So... while I wrap the logger used in the `moduleSpecifierTransform()` which is called by the `nodeResolve()` middleware, I was referencing the un-wrapped (i.e. un-levelled) version of the logger in the closure called for individual specifier resolution.  I modified code to use the intended logger.  This involved passing it around in a few more function parameters.  If I had more to pass around I might convert things to classes, but I'm okay with adding a logger parameter to these functions.
