### ISSUE TITLE
Turn on *all* the babel syntax features, so middleware works in more cases

### ISSUE THREAD

**Issue by usergenic** [Polymer/koa-node-resolve#4]
Right now the JavaScript parsing will blow up when non-default syntax encountered.  If this middleware is going to be helpful for developers, it needs to support any syntax babel parser supports.

**Comment by usergenic** [comment]
I am also exploring ways to just support the `.babelrc` and syntax plugins of the project where the middleware is running, since this will give the user more flexibility.

**Comment by usergenic** [comment]
Maybe https://github.com/Polymer/koa-node-resolve/pull/5 is a sufficient solution to this, in that it enables custom parser configuration etc?

**Comment by aomarks** [comment]
I did immediately hit missing dynamic import syntax issue. I do think defaulting to supporting all the latest ES syntax would be the best default, and IIUC the syntax plugins are pretty much free to have as dependencies since they're really just parser flags.

**Comment by usergenic** [comment]
Okay.  Probably should constrain to adding all the syntax plugins that don't have options.  Things get dicey once they have options.

**Comment by usergenic** [comment]
Fixed by https://github.com/Polymer/koa-node-resolve/pull/12
